name: adv2020
version: 0.1.0.0
github: "ixialumy/adv2020"
license: BSD3
author: "Jonas Paus"
maintainer: "pausjonas@gmail.com"
copyright: "2022 Jonas Paus"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/adv2020#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - split >= 0.2
  - extra

library:
  source-dirs: src

executables:
  adv2020-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adv2020
  # adv01-exe:
  #   main: Adv01.hs
  #   source-dirs: src
  # adv02-exe:
  #   main: Adv02.hs
  #   source-dirs: src
# tests:
# adv2020-test:
#   main:                Spec.hs
#   source-dirs:         test
#   ghc-options:
#   - -threaded
#   - -rtsopts
#   - -with-rtsopts=-N
#   dependencies:
#   - adv2020
